config/routes.rb
Polsci630::Application.routes.draw do
  get "password_resets/new"
  root 'static_pages#home'

  get '/home' => 'static_pages#home'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/info/' => 'static_pages#info'

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :assignments
  resources :meetings

  resources :users
  resources :students, controller: 'users', only: [:show] do
    resources :homework_documents, only: [:new, :create, :edit, :update]
  end
  resources :teachers, controller: 'users', only: [:show]

  resources :homework_documents, only: [:index]

  resources :sessions, only: [:create]

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :meeting_materials
  accepts_nested_attributes_for :meeting_materials, 
    allow_destroy: true,
    reject_if: :all_blank
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def show
    @meeting = Meeting.find(params[:id])
  end

  def index
    @meetings = Meeting.all
  end

  def new
    @meeting = Meeting.new
    3.times { @meeting.meeting_materials.new }
  end

  def edit
    @meeting = Meeting.find(params[:id])
    n = [0, 3 - @meeting.meeting_materials.count].max
    n.times { @meeting.meeting_materials.new }
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.time = parse_time_with_correct_zone(params[:meeting][:time])
    if @meeting.save
      User.all.active.each do |user|
        UserMailer.notify_new_meeting(@meeting, user).deliver!
      end 
      flash[:success] = "Meeting created"
      redirect_to @meeting
    else
      flash.now[:error] = "Unable to create meeting"
      render :new
    end
  end

  def update
    @meeting = Meeting.find(params[:id])
    @meeting.time = parse_time_with_correct_zone(params[:meeting][:time])
    if @meeting.update_attributes(meeting_params)
      flash[:success] = "Meeting updated"
      redirect_to @meeting
    else
      flash.now[:error] = "Unable to save changes"
      render :edit
    end
  end

  def destroy
    Meeting.find(params[:id]).destroy
    flash[:success] = "Meeting deleted"
    redirect_to root_path
  end

  private

    def meeting_params
      params.require(:meeting)
            .permit(:title,
                    meeting_materials_attributes: [:id, :material, 
                                                   :_destroy])
    end
end

app/views/meetings/_form.html.erb
<%= form_for @meeting, :html => { :multipart => true } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :time %>
  <%= f.text_field :time, value: time_format(f.object.time), 
                                  class: "datetimepicker" %>

  Materials:
  <ul>
    <%= f.fields_for :meeting_materials, :html => { :multipart => true } do |materials_form| %>
      <li>
        <% if materials_form.object.material.exists? %>
          <%= link_to materials_form.object.material_file_name,
                      materials_form.object.material.url %>
          <%= materials_form.label :_destroy, class: "checkbox inline" do %>
            Remove attachment <%= materials_form.check_box :_destroy %>
          <% end %>
        <% else %>
          <%= materials_form.label :material %>
          <%= materials_form.file_field :material %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= f.submit "Submit", class: "btn btn-large" %>
<% end %>

app/views/meetings/edit.html.erb
<% provide(:title, "Edit meeting") %>

<h3>Edit meeting</h3>

<div class="row">
  <div class="span6">
    <%= render partial: 'form' %>
  </div>

  <% if current_user.teacher? %>
    <%= link_to "Delete meeting (careful!)", meeting_path(@meeting), method: "DELETE",
        data: { confirm: "You sure?" }, 
        class: "btn btn-large btn-danger" %>
  <% end %>
</div>

app/views/meetings/index.html.erb
<% provide(:title, "Meeting list") %>

<h3>List of all meetings</h3>

<div class="row">
<div class="span9" >
<table class="table table-hover">
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Time</th>
    <th scope="col">Materials</th>
  </tr>
  <% @meetings.order("id ASC").each do |meeting| %>
    <tr>
      <td><%= link_to meeting.title, meeting %></td>
      <td><%= meeting.time.strftime("%m/%d/%Y %H:%M %Z") %></td>
      <td>
        <% meeting.meeting_materials.each do |meeting_material| %>
          <ul>
            <%= link_to meeting_material.material_file_name, 
                        meeting_material.material.url %>
          </ul>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
</div>
</div>

app/views/meetings/new.html.erb
<% provide(:title, "Create meeting") %>

<h3>Create meeting</h3>

<div class="row">
  <div class="span6">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/meetings/show.html.erb
<% provide(:title, "Meeting") %>

<h3><%= @meeting.title %></h3>

<p><%= @meeting.time.strftime("%m/%d/%Y %H:%M %Z") unless @meeting.time.nil? %></p>

<h4>Materials</h4>
<ul>
  <% @meeting.meeting_materials.each do |meeting_material| %>
    <li><%= link_to meeting_material.material_file_name, 
                    meeting_material.material.url %>
    </li>
  <% end %>
</ul>

<% if !current_user.nil? && current_user.teacher? %>
  <% @teacher = current_user %>
  <%= link_to "Edit meeting", edit_meeting_path(@meeting), class: "btn" %>
<% end %>