config/routes.rb
Polsci630::Application.routes.draw do
  get "password_resets/new"
  root 'static_pages#home'

  get '/home' => 'static_pages#home'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/info/' => 'static_pages#info'

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :assignments
  resources :meetings

  resources :users
  resources :students, controller: 'users', only: [:show] do
    resources :homework_documents, only: [:new, :create, :edit, :update]
  end
  resources :teachers, controller: 'users', only: [:show]

  resources :homework_documents, only: [:index]

  resources :sessions, only: [:create]

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  has_many :homework_documents, inverse_of: :assignment
  has_attached_file :document
  has_attached_file :source_code
  has_attached_file :solution
  has_attached_file :solution_source_code
  validates :deadline, presence: true
  validates :title, presence: true, allow_blank: false

  validates_attachment :document, presence: true,
    size: { in: 0..10.megabytes }
  before_document_post_process :set_document_content_type

  validates_attachment :source_code, presence: true,
    size: { in: 0..10.megabytes }

  validates_attachment :solution,
    size: { in: 0..10.megabytes }
  before_solution_post_process :set_solution_content_type

  validates_attachment :solution_source_code,
    size: { in: 0..10.megabytes }

  scope :closed,   -> { where("deadline < ?", 1.hour.ago) }
  scope :open,     -> { where("deadline > ?", 1.hour.ago) }
  scope :graded,   -> { where(graded: true) }
  scope :ungraded, -> { where(graded: false) }

  def grader
    submitter_ids = "SELECT submitter_id FROM homework_documents
                     WHERE assignment_id = :assignment_id"
    Student.where("id IN (#{submitter_ids})", assignment_id: id)
  end

  def Assignment.deadline_reminder
    open.each do |assigment|
      if Time.zone.now > assignment.deadline - 1.day
        Student.all.each do |student|
          unless student.submitted_homework_documents.map(&:assignment_id).include? assignment.id
            UserMailer.notify_closing_deadline(student, assignment).deliver!
          end
        end 
      end
    end
  end

  def Assignment.grade_all
    closed.ungraded.each do |assignment|
      assignment.assign_homework_doc_to_grader  
    end
  end

  def assign_homework_doc_to_grader
    students = grader
    a = students.shuffle
    # a is the shuffled list of student. "Rotate" that by one position, we match each person to another
    # We zip together the unrotated and the rotated array, then convert to a hash
    grader_map_to_submitter = Hash[*a.zip(a.rotate(1)).flatten]

    grader_map_to_submitter.each do |grader, submitter|
      doc = submitter.submitted_homework_documents.where(assignment_id: id).last
      doc.update_attribute(:grader_id, grader.id)
      UserMailer.notify_pending_grading(grader, self).deliver!
    end
    update_attribute(:graded, true)
  end

  private

    def set_document_content_type
      self.document.instance_write(:content_type, MIME::Types.type_for(self.document_file_name).first.content_type.to_s)
    end

    def set_solution_content_type
      self.solution.instance_write(:content_type, MIME::Types.type_for(self.solution_file_name).first.content_type.to_s)
    end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :turn_away_non_teacher, only: [:new, :edit, :update, :destroy]

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params)
    @assignment.deadline = parse_time_with_correct_zone(params[:assignment][:deadline])
    if @assignment.save
      User.all.active.each do |user|
        UserMailer.notify_new_assignment(@assignment, user).deliver!
      end
      flash[:success] = "Assignment posted"
      redirect_to @assignment
    else
      flash[:error] = "Homework has not been submitted"
      render :new
    end
  end

  def show
    @assignment = Assignment.find(params[:id])
  end

  def index
    @assignments = Assignment.all
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def update
    @assignment = Assignment.find(params[:id])
    @assignment.deadline = parse_time_with_correct_zone(params[:assignment][:deadline])
    if @assignment.update_attributes(assignment_params)
      flash[:success] = "Assignment updated"
      redirect_to @assignment
    else
      flash.now[:error] = "Unable to save changes"
      render :edit
    end
  end

  def destroy
    Assignment.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end

  private

    def assignment_params
      params.require(:assignment)
            .permit(:title, :body,
                    :max_grade, :document, :source_code,
                    :solution, :solution_source_code)
    end

    def turn_away_non_teacher
      redirect_to user_path(current_user), notice: "You are not allowed to do that" unless current_user.teacher?
    end
end

app/views/assignments/edit.html.erb
<% provide(:title, "Edit assignment") %>
<h1>Edit assignment</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@assignment) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :body %>
      <%= f.text_area :body %>

      <%= f.label :deadline %>
      <%= f.text_field :deadline, value: time_format(f.object.deadline), 
                                  class: "datetimepicker" %>

      <%= f.label :max_grade %>
      <%= f.number_field :max_grade %>

      <%= f.label :document %>
      <%= f.file_field :document %>

      <%= f.label :source_code %>
      <%= f.file_field :source_code %>

      <%= f.label :solution %>
      <%= f.file_field :solution %>

      <%= f.label :solution_source_code %>
      <%= f.file_field :solution_source_code %>

      <br>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <% if current_user.teacher? %>
      <%= link_to "Delete assignment (careful!)", assignment_path(@assignment), method: "DELETE",
        data: { confirm: "You sure? This will delete this assignment and all submitted works." }, 
        class: "btn btn-large btn-danger" %>
    <% end %>
  </div>
</div>

app/views/assignments/index.html.erb
<% provide(:title, 'All assignments') %>
<h1>All assignments</h1>

<div class="row">
<div class="span6" >
<table class="table table-hover">
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Deadline</th>
    <th scope="col">Status</th>
  </tr>
  <% @assignments.order("id ASC").each do |assignment| %>
    <tr>
      <td><%= link_to assignment.title, assignment %></td>
      <td><%= assignment.deadline.strftime("%m/%d/%Y %H:%M") %></td>
      <td><%= assignment.deadline < 1.hour.ago ? "Closed" : "Open" %>, 
          <%= assignment.graded ? "Graded" : "Ungraded" %></td>
    </tr>
  <% end %>
</table>
</div>
</div>

app/views/assignments/new.html.erb
<% provide(:title, 'New assignment') %>
<h1>Post new assignment</h1>

<div class="container">
  <div class="span6">
    <%= form_for @assignment, :html => { :multipart => true } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <!-- student_id is passed along due to nested route -->
      <%#= f.hidden_field :student_id, student_id %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :body %>
      <%= f.text_area :body %>

      <%= f.label :deadline %>
      <%= f.text_field :deadline, value: time_format(f.object.deadline), 
                                  class: "datetimepicker" %>

      <%= f.label :max_grade %>
      <%= f.number_field :max_grade %>

      <%= f.label :document %>
      <%= f.file_field :document %>

      <%= f.label :source_code %>
      <%= f.file_field :source_code %>

      <%= f.submit "Post assignment", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/assignments/show.html.erb
<% provide(:title, @assignment.title) %>
<h1>Assignment: <%= @assignment.title %></h1>

<p>Deadline: <%= @assignment.deadline.strftime("%m/%d/%Y %H:%M %Z") %></p>
<p>Max grade: <%= @assignment.max_grade %></p>
<p><%= @assignment.body %></p>

<ul>
  <li><%= link_to "Assignment", @assignment.document.url %></li>
  <li><%= link_to "Assignment source code", @assignment.source_code.url %></li> 
  <li><%= @assignment.solution_file_name.nil? ?
            "Solution not yet available" :
            link_to("Solution", @assignment.solution.url) %></li>
  <li><%= @assignment.solution_source_code_file_name.nil? ?
            "Solution code not yet available" :
            link_to("Solution source code", @assignment.solution_source_code.url) %></li>
</ul>

<% if !current_user.nil? && current_user.student? %>
  <% @student = current_user %>
  <%= link_to "Submit your work", new_student_homework_document_path(student_id: @student.id), class: "btn" %>
<% elsif !current_user.nil? && current_user.teacher? %>
  <% @teacher = current_user %>
  <%= link_to "Edit assignment", edit_assignment_path(@assignment), class: "btn" %>
<% end %>