config/routes.rb
Polsci630::Application.routes.draw do
  get "password_resets/new"
  root 'static_pages#home'

  get '/home' => 'static_pages#home'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/info/' => 'static_pages#info'

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :assignments
  resources :meetings

  resources :users
  resources :students, controller: 'users', only: [:show] do
    resources :homework_documents, only: [:new, :create, :edit, :update]
  end
  resources :teachers, controller: 'users', only: [:show]

  resources :homework_documents, only: [:index]

  resources :sessions, only: [:create]

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  before_create :create_hashed_token

  validates :name, presence: true, length: { maximum: 30 }, allow_blank: false
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, allow_blank: false,
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 6 }

  has_secure_password

  scope :active, -> { where("is_active is TRUE") }

  def User.new_raw_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(raw_token)
    Digest::SHA1.hexdigest(raw_token.to_s)
  end

  def send_password_reset
    self.update_attribute(:password_reset_token, User.digest(User.new_raw_token))
    self.update_attribute(:password_reset_sent_at, Time.zone.now)
    UserMailer.password_reset(self).deliver!
  end

  def student?
    type == "Student"
  end

  def teacher?
    type == "Teacher"
  end

  private

    def create_hashed_token
      self.hashed_token = User.digest(User.new_raw_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :force_user_to_sign_in, only: [:show, :edit, :update, :index, :destroy]
  before_action :turn_away_wrong_user, only: [:show, :edit, :update, :destroy]
  before_action :turn_away_non_teacher, only: [:destroy]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @type_options = type_options
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver!
      flash[:success] = "Welcome to the TA app"
      sign_in @user
      redirect_to @user
    else
      flash.now[:error] = "Unable to create your account"
      @type_options = type_options
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      UserMailer.notify_setting_change(@user).deliver!
      flash[:success] = "Your profile has been updated."
      redirect_to @user
    else
      flash.now[:error] = "Unable to save changes."
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:type, :name, :email, 
                                   :password, :password_confirmation)
    end

    def force_user_to_sign_in
      redirect_to signin_path, notice: "Please sign in" unless signed_in?
    end

    def turn_away_wrong_user
      @correct_user = User.find(params[:id])
      redirect_to root_path, notice: "You are not allowed to do that" unless current_user?(@correct_user) || current_user.teacher?
    end

    def turn_away_non_teacher
      redirect_to root_path, notice: "You are not allowed to do that" unless current_user.teacher?
    end

    def type_options
      [['Student', 'Student'], ['Teacher', 'Teacher']]
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_student.html.erb
<div class="row center">
<h3>Visualization of your performance</h3>
<%= content_tag "div", id: "grade_bargraph", class: "span6", 
  data: { :finalgrades => @student.submitted_homework_documents.map(&:final_grade) } do %>
<% end %>

<%= content_tag "div", id: "grade_scatterplot", class: "span6",
  data: { :submissions => 
    @student.submitted_homework_documents.map { 
      |sub| [sub.assignment.title, sub.grade, (sub.created_at - sub.assignment.deadline) / 3600 ] 
    }
  } do %>
<% end %>
</div>

<div class="center">
<%= link_to "Submit new homework here", new_student_homework_document_path(student_id: @student.id), class: "btn btn-large btn-primary" %>
</div>

<div class="span12">
<h3>Your submissions:</h3>
<table class="table table-hover">
  <tr>
    <th scope="col">Assignment title</th>
    <th scope="col">Submission date</th>
    <th scope="col">Deadline</th>
    <th scope="col">Grade / Penalty / Final grade</th>
  </tr>
  <% @student.submitted_homework_documents.each do |submission| %>
    <tr>
      <td><%= submission.assignment.title %></td>
      <td><%= submission.created_at %></td>
      <td><%= submission.assignment.deadline %></td>
      <td><%= submission.grade.nil? ? "NA" : ("%.1f" % submission.grade) %> / <%= "%.2f" % submission.penalty %> / <%= submission.grade.nil? ? "NA" : ("%.1f" % submission.final_grade) %></td>
      <td>
        <% if submission.ungraded_file.exists? %>
          <%= link_to "Ungraded", submission.ungraded_file.url %>
        <% end %>
      </td>
      <td>
        <% if submission.ungraded_file_source_code.exists? %>
          <%= link_to "Ungraded code", submission.ungraded_file_source_code.url %>
        <% end %>
      </td>
      <td>
        <% if submission.graded_file.exists? %>
          <%= link_to "Graded", submission.graded_file.url %>
        <% end %>
      </td>
      <td>
        <% if submission.graded_file_source_code.exists? %>
          <%= link_to "Graded code", submission.graded_file_source_code.url %>
        <% end %>
      </td>
      <td><%= link_to "Edit your submission", edit_student_homework_document_path(student_id: @student.id, id: submission.id), class: "btn" %></td>
    </tr>
  <% end %>
</table>

<h3>Your grading jobs:</h3>

<h4>Finished</h4>
<table class="table table-hover">
  <tr>
    <th scope="col">Assignment title</th>
    <th scope="col">Grade</th>
    <th scope="col">Attachment</th>
  </tr>
  <% @student.returned_homework_documents.commented.each do |graded_doc| %>
    <tr>
      <td><%= graded_doc.assignment.title %></td>
      <td><%= graded_doc.grade %></td>
      <td><%= link_to "Ungraded", graded_doc.ungraded_file.url %></td>
      <td><%= link_to "Ungraded code", graded_doc.ungraded_file_source_code.url %></td> 
      <td><%= link_to "Graded", graded_doc.graded_file.url %></td>
      <td><%= link_to "Graded code", graded_doc.graded_file_source_code.url %></td>
      <td><%= link_to "Re-grade", edit_student_homework_document_path(student_id: graded_doc.submitter_id, id: graded_doc.id), class: "btn" %></td>
    <% end %>
  </tr>
</table>

<h4>Unfinished</h4>
<table class="table table-hover">
  <tr>
    <th scope="col">Assignment title</th>
    <th scope="col">Attachment</th>
  </tr>
  <% @student.returned_homework_documents.uncommented.each do |ungraded_doc| %>
    <tr>
      <td><%= ungraded_doc.assignment.title %></td>
      <td><%= link_to "Ungraded", ungraded_doc.ungraded_file.url %></td>
      <td><%= link_to "Ungraded code", ungraded_doc.ungraded_file_source_code.url %></td>
      <td><%= link_to "Grade", edit_student_homework_document_path(student_id: ungraded_doc.submitter_id, id: ungraded_doc.id), class: "btn" %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/users/_teacher.html.erb
<h1>Teacher profile</h1>

<%= link_to "Create new meeting", new_meeting_path %>
<br>
<%= link_to "Create new assignment", new_assignment_path %>
<br>
<%= link_to "Grade homeworks", homework_documents_path %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, as: :user, url: user_path(@user.id) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :is_active do %>
        I want to actively enrolled <%= f.check_box :is_active, class: "checkbox inline" %>
      <% end %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large" %>
    <% end %>

    <% if current_user?(@user) || current_user.teacher? %>
      <%= link_to "Delete account (careful!)", user_path(@user), method: "DELETE",
        data: { confirm: "You sure? This will delete everything in your account." }, 
        class: "btn btn-large btn-danger" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, as: :user, url: users_path, method: 'POST' do |f| %>
      <%#= @user.becomes(User) is equivalent with @user, as: :user %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :type %>
      <%= f.select :type, @type_options %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create account", class: "btn btn-large" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<% if @user.student? %>
  <% @student = @user %>
  <%= render partial: 'student' %>
<% elsif @user.teacher? %>
  <% @teacher = @user %>
  <%= render partial: 'teacher' %>
<% end %>