config/routes.rb
Polsci630::Application.routes.draw do
  get "password_resets/new"
  root 'static_pages#home'

  get '/home' => 'static_pages#home'
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/info/' => 'static_pages#info'

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :assignments
  resources :meetings

  resources :users
  resources :students, controller: 'users', only: [:show] do
    resources :homework_documents, only: [:new, :create, :edit, :update]
  end
  resources :teachers, controller: 'users', only: [:show]

  resources :homework_documents, only: [:index]

  resources :sessions, only: [:create]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">TA app</a>
    by Anh Le
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%#= link_to image_tag("unhelpful-teacher.jpg", alt: "Unhelpful Teacher"), root_path %>
      <nav>
        <ul class="nav pull-left">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <!-- <li><%= link_to "Users", users_path %></li> -->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Work Station", current_user %></li>
                <li><%= link_to "Profile Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
          <li><%= link_to "Assignments", assignments_path %></li>
          <li><%= link_to "Meetings", meetings_path %></li>
          <li><%= link_to "Misc info", info_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>